langguage: go

go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz
  - tar -zxf hugo_0.31.1_Linux-64bit.tar.gz
  - chmod a+x hugo

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: ./public
  repo: git@github.com:hulb/hulb.github.io.git
  email: hulb@live.cn
  target_branch: master
